### PR TITLE
Fixes net451 issues

### LINKED ISSUE #45: Unable to use NUnit Runner with .NET 4.5.2
To reproduce it:
```javascript
{
  "version": "1.0.0-*",
  "testRunner": "nunit",
  "dependencies": {
    "MyClassLibrary": { "target": "project" },
    "NUnit": "3.4.0",
    "dotnet-test-nunit": "3.4.0-beta-1"
  },
  "frameworks": {
    "net452":  {}, 
    "netcoreapp1.0": {
      "imports": [
        "portable-net45+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    }
  }
}
```
Run:
```
dotnet test test\MyClassLibrary.Tests -f net452
```
Exception:
```
NUnit .NET Core Runner 3.4.0
Copyright (C) 2016 Charlie Poole
Runtime Environment
    OS Platform: Windows
     OS Version: 6.1.7601
        Runtime: win7-x64
Test Files
    C:\path\to\project\bin\Debug\net452\win7-x64\MyClassLibrary.Tests.dll
System.DllNotFoundException: Unable to load DLL 'Microsoft.DiaSymReader.Native.amd64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Extensions.Testing.Abstractions.FullPdbReader.CreateSymReader64(Guid& id, Object& symReader)
   at Microsoft.Extensions.Testing.Abstractions.FullPdbReader.CreateNativeSymReader(Stream pdbStream)
   at Microsoft.Extensions.Testing.Abstractions.FullPdbReader..ctor(Stream pdbStream)
   at Microsoft.Extensions.Testing.Abstractions.PdbReaderFactory.Create(String pdbPath)
   at Microsoft.Extensions.Testing.Abstractions.SourceInformationProvider..ctor(String pdbPath, IPdbReaderFactory pdbReaderFactory)
   at NUnit.Runner.Navigation.NavigationDataProvider.GetNavigationDataProvider(String assemblyPath)
   at NUnit.Runner.TestRunner.Execute()
   at NUnit.Runner.TestRunner.Run(String[] args)
```

YMMV with other runtimes, but you will get similar errors.

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
Fix #45
And possibly #37

### CODE REVIEW

**Comment by rprouse** [comment]
AppVeyor failure is an incompatible branch name.

**Comment by rprouse** [comment]
Looks good. I assume you have tested it?

**Comment by jasonwilliams200OK** [comment]
@rprouse, based on the multiple conversations in dotnet/cli, xunit/xunit and xunit/dotnet-test-xunit, I believe this is the most appropriate fix for these issues (as consumers of package won't need to add any extra dependency in their project); but since I cannot reproduce #45 on my system or AppVeyor, we would need to wait for @ejball's reply for this comment: https://github.com/nunit/dotnet-test-nunit/issues/45#issuecomment-233147685. :)

**Comment by jasonwilliams200OK** [comment]
@rprouse, @elbaloo confirmed that this patch fixes the issue. Should we merge this for next beta?

**Comment by rprouse** [comment]
Looks good, thanks. I am planning on doing an RC or beta this week. Anything you think we should make sure we include?

**Comment by jasonwilliams200OK** [comment]
Thanks. I think with command line argument parsing included, this is going to be a great update! As such, I can't think of anything of release-blocker nature. However, I will keep an eye on issues. :)

**Pull request merged**
