### PR TITLE
Test parameter parsing out of framework

### PR DESCRIPTION
**Pull request by jnm2**
Umbrella: https://github.com/nunit/nunit/issues/1941

### CODE REVIEW

**Comment by jnm2** [comment]
Looks like https://github.com/nunit/nunit.portable.agent/pull/20 is going to need to be published before this build can complete.

**Comment by CharliePoole** [comment]
Is there an issue for this?

**Comment by jnm2** [comment]
> Is there an issue for this?

I can create one if nunit/nunit#1941 can't be linked in dotnet-test-nunit release notes,

**Comment by CharliePoole** [comment]
@jnm2 You could, create an issue, which I would then classify for discussion, but that seems a little heavier-weight than we need to be. The point of my question is that the @nunit/net-core-runner-team has not created an issue for this and therefore could be presumed to not want it. Let's wait for them.

All the "core" projects are experimental and at this point their continued existence is in doubt because microsoft is changing how you use .NET core and run tests. We may not want to spend time on this. However, I myself don't work on those projects, so I can't tell you.

@rprouse Is this something we should be working on?

**Comment by jnm2** [comment]
I'm with you, but it was important to me that this PR is defensive. It provides rationale to future development and prepares improvements to be made using IDictionary rather than the deprecated string method.

**Comment by rprouse** [comment]
I don't mind merging this. We will likely do one more release of this adapter to hold people over as .NET Core switches over to the MSBUILD/CSPROJ format which will make this project obsolete. I don't think we need an issue for this, I will just mark the PR accordingly.

First check of the code looks good, but I need to check CI and see why they are failing.

**Comment by rprouse** [comment]
I see CI is failing because of the other PR you submitted. I have merged that. Once it is built on master, this PR should be switched to use the NuGet package from that build.

**Comment by CharliePoole** [comment]
There's a change requested in one of the other PRs (?? I'm on my phone) to put the dictionary creation into options. Up to you whether you want to keep in sync.

**Comment by dougkpowers** [comment]
@rprouse we are behind on the [3.4 milestone](https://github.com/nunit/dotnet-test-nunit/milestone/6).  Are we waiting on this PR?  Either way, it would be nice to get the latest round of fixes out for consumption without us having to manage side-builds.

**Comment by rprouse** [comment]
@dougkpowers we are not waiting on this PR, we are waiting on the NUnit Framework and Console 3.6 releases which should go out this week and next week. They take priority at the moment.

@jnm2 do you think you can update this PR to use the NuGet that includes the changes in nunit/nunit.portable.agent#20 to get CI passing?

**Comment by jnm2** [comment]
@rprouse I just change the project.json package references, right? Where do I look up the new version string to use?

**Comment by rprouse** [comment]
@jnm2 yes just changing the project.json should work. It doesn't seem to be publishing to MyGet, so use the AppVeyor `3.3.0.97-CI`

**Comment by jnm2** [comment]
All working except I didn't find the tests. Side effect of not being able to use Visual Studio for the edits in this repo. Fix coming.

**Comment by jnm2** [comment]
All working now.

**Comment by jnm2** [comment]
All working now. The Travis XCode tests could use a kick.

**Comment by rprouse** [comment]
We've been having trouble with the IOS builds on Travis, so we can ignore those.

**Comment by jnm2** [comment]
This project is at the end of its life, so no need for this PR.

**Pull request closed without merging**
