### PR TITLE
#111 Add the supporting of Visual Studio Test Platform

### PR DESCRIPTION
**Pull request by NikolayPianikov**
- Move to the project model of VS 2017
- Create the test adapter for Visual Studio Test Platform

### CODE REVIEW

**Comment by rprouse** [comment]
@NikolayPianikov this is great work and I appreciate the effort, but this wasn't the approach we were planning on taking with this. If we update this project this way, it will break anyone using the old project.json format. The main issue though is that our current VS adapter implements the required interface, it just needs to be updated to support .NET Core.

My latest thinking is that the nunit.portable.agent isn't the best approach either. It duplicates much of the code in the Engine such as filters, a driver, aggregating test runs, etc. I have been wavering between adding the functionality to the portable agent, or using a .NET Standard version of the engine.

I am open to discussing or help with the project, but I am not sure this is the right place to be doing the work.

**Comment by rprouse** [comment]
Also, notice in the article that you linked to, neither xUnit nor MSTest converted their dotnet-test-* adapters to support the new (old) adapter API, but instead extended their original adapters.

**Comment by NikolayPianikov** [comment]
Ok
I understand your point. I just supposed that it is a main direction how NUnit will be developed for .net core (by the way this adapter also supports and other frameworks)
I believe the [this](https://blogs.msdn.microsoft.com/visualstudioalm/2016/11/29/evolving-the-test-platform-part-3-net-core-convergence-and-cross-plat/) is very promising and quite extensible approach for CI. For example we have [TeamCity logger](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter) which works for all test engines and user should make a minimum efforts to have a CI integration. Also we are planing add some other abilities like a reordering of tests, a gathering of the code coverage, unit tests for memory consumsion and so on. And I am looking forward when we will have a test adapter supporting Visual Studio Test Platform. But I wanted  to note that this PR is quite simple, was tested by me during some time and it is suitable for us :)

**Comment by wallymathieu** [comment]
So what's the status?

**Comment by wallymathieu** [comment]
Could we make a fork of this library based on @NikolayPianikov with the needed changes?

**Comment by rprouse** [comment]
I am closing this pull request. We already have a working copy of the proper adapter at nunit/nunit3-vs-adapter#313 and you can track progress at nunit/nunit3-vs-adapter#297. I also put a very initial demo project using the adapter at https://github.com/rprouse/NUnitPlatformTests

I am having trouble getting AppVeyor to build the adapter using VS2017, but other than that, it is very close to ready for an alpha release.

**Comment by rprouse** [comment]
BTW, @NikolayPianikov if you want to help out in the other adapter project, I could use the help 👍

**Pull request closed without merging**
