### PR TITLE
Issue-26: Small units of time should default to 1 tick

### LINKED ISSUE #26: Set duration to 1 tick for Ignored Tests
Currently I am using the minimum duration of 1ms.  See line 88 in TestConverter in the NUnit3TestAdapter project.

### PR DESCRIPTION
**Pull request by jplebre**
What about any value lower than 1ms?
Waiting until I can run tests, but meanwhile let's chat about this

Fixes #26

### CODE REVIEW

**Comment by jplebre** [comment]
Very sorry for this, doing the tdd cycle using CI since you wanted to push this out this w-end.
I'll squash commits later

**Comment by jplebre** [comment]
continuous-integration/travis-ci/pr

**Comment by rprouse** [comment]
Sorry I haven't got back to you, I have family over from England. On my phone, so short response. :smile:

To run tests locally, dotnet run the runner project under test. It is an nunitlite project. I haven't figured out how to self test with the .NET Core runner.

**Comment by jplebre** [comment]
No worries, i've used CI as my TDD cycle (*cough*)
Whenever you have time let me know what you think, I've made it so it only defaults to 1tick when the test was skipped.
I'll rebase when i get home

**Comment by rprouse** [comment]
I will take a look today. Prepping for a sprint review, will take a look after the meeting.

**Comment by jasonwilliams200OK** [comment]
> I'll rebase when i get home

Don't worry, we can squash the commits before merging: https://github.com/blog/2141-squash-your-commits, where the PR has couple of un-squashed intermediate commits.

**Comment by rprouse** [comment]
Looks good, thanks :+1:

**Pull request merged**
